needs-artifacts:
  image: alpine:3.14
  stage: test
  needs:
  - quick
  script:
  - ls -l date.txt
  variables: {}
needs-no-artifacts:
  image: alpine:3.14
  stage: test
  needs:
  - job: quick
    artifacts: false
  script:
  - mkdir date.txt
  variables: {}
quick:
  image: alpine:3.14
  stage: build
  script:
  - date > date.txt
  artifacts:
    paths:
    - date.txt
  variables: {}
stages:
- build
- test
- last
variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
default: {}
