stages:
- build

.template_1: &template_1_def
  image: ubuntu:18.04


job-build-one:
  <<: *template_1_def
  stage: build
  script:
  - pwd
  - ls -l

linux-job-runner:
  stage: build
  image: ubuntu:18.04
  before_script:
    - apt-get update
    - apt-get install -y python
  script:
    - python locallab.py job-build-one

windows-job-runner:
  stage: build
  tags:
    - cunity-windows-docker-1803
  script:
    - c:\Python27\python locallab.py .windows-job

.windows-job:
  image:
    name: cunity/windows-1803-cmake:latest
    entrypoint:
      - "powershell.exe"
  stage: build
  script:
    - dir
    - pwd


