stages:
- build

.template_1: &template_1_def
  image: ubuntu:18.04


job-build-docker:
  <<: *template_1_def
  stage: build
  script:
  - pwd
  - ls -l

.job-build-shell:
  stage: build
  script:
  - pwd
  - ls -l


linux-job-runner:
  variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: build
  image: docker:stable-git
  before_script:
    - apk add python2
    - apk add py2-pip
    - pip install -e .
  script:
    - locallab.py job-build-docker
    - locallab.py .job-build-shell

windows-docker-job-runner:
  stage: build
  tags:
    - cunity-windows-docker-1803
  script:
    - c:\Python27\python locallab.py .windows-docker-job

.windows-docker-job:
  image:
    name: cunity/windows-1803-cmake:latest
    entrypoint:
      - "powershell.exe"
  stage: build
  script:
    - dir
    - pwd

windows-shell-job:
  stage: build
  tags:
    - cunity-windows-docker-1803
  script:
    - echo %PATH%
    - echo %NUMBER_OF_PROCESSORS%
    - echo %OS%
    - echo %CD%


