include:
  - local: ci-includes/default_runners.yml
  - local: ci-includes/gitlab_runners.yml


emulator-windows-test:
  stage: build
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - echo $PSScriptRoot
    - Get-Content $PSScriptRoot
    - cmd /C 'dsfdsfdsfdsfs || exit /b 1'
    - exit $LASTEXITCODE
