include:
  - "/ci-includes/ubuntu-image.yml"
  - local: "/ci-includes/windows-dir-after.yml"

stages:
- build


job-build-docker:
  extends: .ubuntu-1804-image
  stage: build
  script:
    - pwd
    - ls -l
    - env|grep CI_|sort
    - touch ${CI_JOB_NAME}

job-build-later:
  stage: test
  extends: .ubuntu-1804-image
  needs: [job-build-docker]
  script:
    - ls -l

.job-build-shell:
  stage: build
  script:
  - pwd
  - ls -l

.fail-job:
  stage: build
  image: busybox:latest
  script:
    - df -h
    - /bin/false

linux-job-runner:
  variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: build
  image: docker:stable-git
  before_script:
    - apk add python2
    - apk add py2-pip
    - pip install -e .
  script:
    - locallab.py job-build-docker
    - locallab.py .job-build-shell

windows-docker-job-runner:
  stage: build
  tags:
    - cunity-windows-2019-docker
  script:
    - dir c:\
    - c:\python37\python.exe locallab.py .windows-docker-job

.windows-docker-job:
  image:
    name: cunity/windows-2019-vs2015-cmake:master
    entrypoint:
      - "powershell.exe"
  stage: build
  script:
    - dir
    - pwd

windows-shell-job:
  extends: .windows-dir-after
  stage: build
  tags:
    - cunity-windows-2019-docker
  script:
    - echo %PATH%
    - echo %NUMBER_OF_PROCESSORS%
    - echo %OS%
    - echo %CD%
    - echo sleeping..
    - powershell -c "Start-Sleep -s 5"
    - echo done


