include:
  - local: ci-includes/alpine-image.yml
  - local: ci-includes/subdir/jobs.yml

stages:
- build
- test

.fail-job:
  stage: build
  image: busybox:latest
  script:
    - df -h
    - /bin/false

linux-testing:
  image: python:3.7
  stage: build
  script:
    - cd emulator
    - pip install pytest
    - pip install -e .
    - python -m pytest . --junit-xml=test-results.xml
  artifacts:
    reports:
      junit:
        - emulator/test-results.xml

linux-job-runner:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: build
  timeout: 15m
  image: docker:stable-git
  before_script:
    - cd emulator
    - apk add python3
    - apk add py3-pip
    - pip install -e .
  script:
    - locallab.py -c ../test-ci.yml --full linux-build-later
    - locallab.py -c ../test-ci.yml linux-docker-job
    - HERE=$(pwd)
    - cd /tmp && locallab.py -c ${HERE}/../test-ci.yml linux-shell-job

windows-job-runner:
  stage: build
  when: manual
  allow_failure: true
  tags:
    - cunity-windows-2019-docker
  script:
    - cd emulator
    - c:\python37\python.exe locallab.py -c ..\test-ci.yml windows-docker-job || exit /b
    - c:\python37\python.exe locallab.py -c ..\test-ci.yml windows-shell-job || exit /b



