quick:
  image: alpine:3.14
  stage: build
  script:
  - date > date.txt
  artifacts:
    paths:
    - date.txt
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
stages:
- build
- test
- last
variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
default:
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
