include:
  - "/ci-includes/ubuntu-image.yml"
  - local: "/ci-includes/windows-dir-after.yml"

stages:
- build
- test

ubuntu-test:
  extends: .ubuntu-1804-image
  stage: build
  script:
  - uname -a

windows-docker-job:
  extends: .windows-dir-after  
  image:
    name: cunity/windows-2019-vs2015-cmake:master
    entrypoint:
      - "powershell.exe"
  stage: build
  script:
    - dir
    - pwd

windows-shell-job:
  extends: .windows-dir-after  
  stage: build
  tags:
    - cunity-windows-2019-docker
  script:
    - echo %PATH%
    - echo %NUMBER_OF_PROCESSORS%
    - echo %OS%
    - echo %CD%
    - echo sleeping..
    - powershell -c "Start-Sleep -s 5"
    - echo done

linux-shell-job
  stage: build
  script:
    - uname -a
    - ls -l

linux-docker-job:
  image: ubuntu:18.04
  stage: build
  script:
    - pwd
    - ls -l
    - env|grep CI_|sort
    - touch ${CI_JOB_NAME}

linux-build-later:
  stage: test
  image: ubuntu:18.04
  needs: [linux-build-docker]
  script:
    - ls -l
