include:
  - ci-includes/alpine-image.yml
  - local: ci-includes/windows-dir-after.yml
  - local: ci-includes/subdir/jobs.yml

stages:
- build
- test

alpine-test:
  extends: .alpine-image
  stage: build
  script:
  - uname -a
  - env|sort
  - sleep 2  # sleep long enough so that test_no_such_exec() has a chance to pass

windows-docker-job:
  extends: .windows-dir-after  
  image:
    name: cunity/windows-2019-vs2015-cmake:master
    entrypoint:
      - "powershell.exe"
  stage: build
  script:
    - dir
    - pwd

windows-shell-job:
  extends: .windows-dir-after  
  stage: build
  tags:
    - cunity-windows-2019-docker
  script:
    - echo $env:PATH
    - echo $env:NUMBER_OF_PROCESSORS
    - echo $env:OS
    - echo sleeping..
    - Start-Sleep -s 5
    - echo done

linux-shell-job:
  stage: build
  script:
    - uname -a
    - ls -l
    - env|sort
    - ls -l ${PWD}/test-ci.yml

.bad-linux-docker-job:
  image: alpine:latest
  stage: build
  script:
    - echo running build bad
    - /bin/false
  after_script:
    - echo running after

linux-docker-job:
  image: alpine:latest
  stage: build
  script:
    - pwd
    - ls -l
    - env|grep CI_|sort
    - touch ${CI_JOB_NAME}

linux-build-later:
  stage: test
  image: alpine:latest
  needs: [linux-docker-job, linux-shell-job]
  variables:
    SOME_VARIABLE: hello
  script:
    - env|grep SOME_VARIABLE

